### ISSUE TITLE
Task: Extend file format for the releases to support family providers

### ISSUE THREAD

**Issue by n3rdc4ptn** [openmcp-project/backlog#110]
### Understand the Task

**Description**
The current file format:
```yaml
name: provider-helm
source: OpenSource
docker:
  image: 
versions:
  - v0.19.0
```

This needs to be extended so it not only is compatible with single providers but also with families. A proposal would be:

```yaml
name: family-providers-aws
source: OpenSource
family:
  parentimage: xpkg.upbound.io/upbound/provider-family-aws
  image: xpkg.upbound.io/upbound/provider-aws-<provider>
  providers:
    - s3
    - ec2
    - ...
versions:
  - v0.52.3
```

The image must be specified with a placeholder for the providers which are listed in there.

### What is required to accept the Task as done.

**Done Criteria**
- [ ] file format is improved in releasechannel-bot to support these family providers
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by dattito** [comment]
Also OCM would not need to be involved here, because it could be just limited on the releasechannel installation level that it is only allowed that a provider can be installed if the dependend providers are also selected for installation by the user.

**Comment by dattito** [comment]
I'd propose a dependency format field (`.dependsOn`), like Crossplane provider families also work ("do not install dependencies automatically, but block installation of the provider until all dependencies are installed by the user").

E.g.:

```yaml
name: provider-family-aws
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-family-aws
versions:
- v2.1.1
---
name: provider-family-aws-account
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-aws-account
dependsOn:
  - name: provider-family-aws
versions:
- v2.1.1
---
name: provider-family-aws-ec2
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-aws-ec2
dependsOn:
  - name: provider-family-aws
versions:
- v2.1.1
```

<details>
  <summary>HOW IT WORKS IN CROSSPANE</summary>
In Crossplane, the installation of providers that have dependencies is just blocked until all providers listed as dependencies are installed "manually" by the user too. There is no automatic installation of dependencies.

Provider Parent:
```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  controller:
    image: xpkg.upbound.io/upbound/provider-family-aws-controller:v2.1.1
```

Provider Child:
```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-family-aws-account
spec:
  controller:
    image: xpkg.upbound.io/upbound/provider-family-aws-account-controller:v2.1.1
  dependsOn:
    - provider:  xpkg.upbound.io/upbound/provider-family-aws
       version: v2.1.1
```


</details>

In this example it would be expected that the family "parent" provider (here called `provider-aws-family`) has to have the same version as the "child" provider (e.g. `provider-family-aws-account` / `provider-family-aws-ec2`).

This means that every child provider is listed on the same level as the "parent" provider of the family. This would allow for other dependency matches besides families, in case there are also other use cases in the future.

Also OCM would not need to be involved here, because it could be just limited on the releasechannel installation level that it is only allowed that a provider can be installed if the dependend providers are also selected for installation by the user.

**Comment by dattito** [comment]
Otherwise if we would like to decouple versions and dependencies (would be a breaking change because `.versions` is now a list of objects, not a list of strings):

```yaml
name: provider-family-aws
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-family-aws
versions:
  - tag: v2.1.1
---
name: provider-family-aws-account
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-aws-account
versions:
  - tag: v2.1.1
    dependencies:
      - name: provider-family-aws
         version: v2.1.1
---
name: provider-family-aws-ec2
source: OpenSource
ga: false
docker:
  image: xpkg.upbound.io/upbound/provider-aws-ec2
versions:
  - tag: v2.1.1
    dependencies:
      - name: provider-family-aws
         version: v2.1.1
```
