### ISSUE TITLE
Task: Extend file format to allow setting the provider to be mirrored (add mirrored property)

### ISSUE THREAD

**Issue by n3rdc4ptn** [openmcp-project/backlog#111]
### Understand the Task

**Description**
The current file format should support mirroring to be specified instead of having a separate process for mirroring images.

Current:
```yaml
name: provider-helm
source: OpenSource
docker:
  image: openmcp.common.repositories.cloud.sap/mirror/provider-helm
versions:
  - v0.19.0
```

Proposal:
```yaml
name: provider-helm
source: OpenSource
docker:
  image: 
mirror:
  target: openmcp.common.repositories.cloud.sap/mirror/provider-helm
versions:
  - v0.19.0
```

For implementation this could be used in conjunction with the new OCM localization feature?

### What is required to accept the Task as done.

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review
