### ISSUE TITLE
Task: Migrate existing e2e (bash-based) test suite to Chainsaw

### ISSUE THREAD

**Issue by In-Ko** [openmcp-project/backlog#149]
### Understand the Task

**Description**
The decision was taken to start using the chainsaw end2end test framework within MCP. This means now it can be started to look at the existing e2e test suite and migrate that to chainsaw.

While doing so, a brief documentation should be created, outlining briefly how, in the MCP context, new chainsaw tests can be created and added to the complete test suite.

### What is required to accept the Task as done.

**Done Criteria**
- [x] The Chainsaw Framework is used to define and execute the existing e2E test suite
- [x] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by Kukkerem** [comment]
# Migrating to Chainsaw for E2E Testing

## Overview

Most of the steps are now migrated to Chainsaw, which provides a structured way to define and run end-to-end tests in Kubernetes environments. This migration aimed to improve test maintainability and automation.

## Limitations of Chainsaw

Despite its advantages, Chainsaw has several notable limitations:

- Conditional step execution is not natively supported.

- Dynamic resource patching is challenging to implement cleanly.

- Combining certain statements with operations is not flexible enough.

- Tools like `wait` and `assert` exist, but:

    - Their scope and API interactions are often unclear.

    - They are inflexible when operating under strict policies or complex testing needs.


## Workarounds


- Many test steps reverted to bash scripts after multiple iterations.

    - These scripts are still controlled by Chainsaw, serving as wrappers for more complex logic.

- A shared helper script handles most of the dynamic logic.

    - This part could be refactored, but the core logic remained unchanged.

- The main resource files were updated, but the shell logic was preserved.

- Avoided using `defer` for resource cleanup, instead relying on Chainsaw’s built-in cleanup mechanism, which deletes resources after test execution.


## Usage

Chainsaw can be used effectively in various e2e test scenarios, even when custom logic is required. Here are some examples:

### 1. Simple Custom Resources

```yaml
- name: step-07-create-btp-subaccount
  cluster: mcp
  try:
    - apply:
      file: manifests/core.openmcp.cloud/subaccount-btp.yaml
```

### 2. Custom Resources with Variables

```yaml
# mcp.yaml
apiVersion: core.openmcp.cloud/v1alpha1
kind: ManagedControlPlane
metadata:
  name: ${MCP_NAME}
  namespace: ${MCP_NAMESPACE}
  labels:
    openmcp.cloud.sap/created-by: "e2e-test"
    openmcp.cloud.sap/test-name: "smoke-test"
spec:
  desiredRegion:
    name: europe
    direction: central
  components:
    apiServer:
      type: GardenerDedicated
    crossplane:
      version: "1.17.1"
      providers:
        - name: btp-account
          version: 0.7.5
    btpServiceOperator:
      version: 0.6.8
    externalSecretsOperator:
      version: 0.8.0
    flux:
      version: 2.12.4
    kyverno:
      version: 3.2.4
    landscaper: {}
  authentication:
    enableSystemIdentityProvider: true
  authorization:
    roleBindings:
      - role: admin
        subjects:
          - kind: User # this is fixed to User, because even with ServiceAccounts we will use identity tokens
            name: "${MCP_SUBJECT_NAME}"
```

```bash
envsubst < ${MANIFEST_FOLDER}/mcp.yaml > ${MANIFEST_FOLDER}/mcp.yaml.tmp && mv ${MANIFEST_FOLDER}/mcp.yaml.tmp ${MANIFEST_FOLDER}/mcp.yaml
```

```yaml
- name: step-04-create-mcp
  cluster: crate
  try:
    - apply:
        file: manifests/core.openmcp.cloud/mcp.yaml
```

### 3. Resource Checks with Bash Scripts

```yaml
- name: step-02-check-workspace-resourcequotas
  try:
    - script:
        timeout: 5m
        content: |
          source ../../pkg/retry.sh || retry 5 kubectl --kubeconfig "${KUBECONFIG_CRATE}" get resourcequota -n "${MCP_NAMESPACE}" workspace
```

## Improvement ideas

- Keep the resource creation in bash and migrate only the API tests to Chainsaw. With this modification, separate tests could be created, and the relevant ones could be selected with the test label selector to create a smoke and a full E2E test suite.

- Refactor run.sh, move the enbsubst logic to the helper file for maintainability.

- Evaluate waits and retries, to migrate them to native Chainsaw format.

- Use input and outputs, bindings to avoid envsubst, and make use of dynamic cluster configs.

- Improve logging in scripts.
