### ISSUE TITLE
Bring Onboarding Provider to `ManagedControlPlane`

### ISSUE THREAD

**Issue by GenosseOtt** [openmcp-project/backlog#68]
**Description**
As a platform admin I want to bring the new Onboarding API Provider to my umbrella ManagedControlPlane
**When Crossplane Provider Onbaording API is enabled in an MCP, we want to automate its trust to the Onboarding API so that end users can order additional MCPs/WS/etc right away.**

```
apiVersion: core.openmcp.cloud/v1alpha1
kind: ManagedControlPlane
metadata:
  name: yo-mcp
spec:
...
  components:
...
    crossplane:
      version: 1.18.0
      providers:
        - name: onboarding-api
          version: 1.0.0
```

## Technical steps
- TBD @reshnm / @gergely-szabo-sap

**Done Criteria**
- [ ] End users can activate provider and Trust between MCP and Onboarding API is accomplished on their behalf
- [ ] Provider can be activated in managed control plane 
- [ ] Provider is visible in CRD browser and release channel
- [ ] End user guide exists

**Comment by GenosseOtt** [comment]
@reshnm & @gergely-szabo-sap  lets follow up on the next steps :-)

**Comment by reshnm** [comment]
First, we could have a manual approach with setting up the required objects on the ManagedControlPlane and the onboarding cluster manually. It would be good to have an operations guide that contains the necessary steps.

An automated step would need to have an additional controller in the mcp-operator.
A project has to be annotated to set up the trust relation between the onboarding cluster and the ManagedControlPlane

```yaml
apiVersion: core.openmcp.cloud/v1alpha1
kind: Project
metadata:
  name: test
  annotations:
    openmcp.cloud/trust-mcp: "<project-name>--<workspace-name>--<mcp-name>"
```

When the responsible controller detects a project with this annotation, it looks up the `.status.components.apiServer.serverAccountIssuer` url and creates a Gardener `OpenIDConnect` resource on the onboarding cluster which established the trust.

In the next step, the user has to authorize the ManagedControlPlane on projects and workspaces:

```yaml
apiVersion: core.openmcp.cloud/v1alpha1
kind: Workspace
metadata:
  name: dev
  namespace: project-test
spec:
  members:
    - kind: User
      name: mcp--<project-name>--<workspace-name>--<mcp-name>:system:serviceaccount:<sa-namespace-on-mcp>:<sa-name-on-mcp>
      roles:
        - admin
```

**Comment by ValentinGerlach** [comment]
In my opinion it would make more sense to have a label or annotation on the `ManagedControlPlane` resource. `OpenIDConnect` resources are cluster-scoped so they don't have a relationship 

The user can then add the `ManagedControlPlane` as a member to a `Project` or `Workspace` either as a `kind: User` (for any MCP service account) or using a special `kind: ManagedControlPlane` (for convenient use of the Onboarding Crossplane Provider).

```yaml
apiVersion: core.openmcp.cloud/v1alpha1
kind: Workspace
metadata:
  name: dev
  namespace: project-test
spec:
  members:
    - kind: ManagedControlPlane
      name: my-mcp
      namespace: project-other--ws-umbrella
      roles:
        - admin
```

The controller responsible for project/workspaces would translate this to a RBAC subject for the `crossplane-provider-onboarding`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example
  namespace: project-test--ws-dev
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: mcp:<uid>:system:serviceaccount:crossplane-system:provider-onboarding
```

Using the MCP's `.metadata.uid` instead of the name prevents that an MCP accidentally gains access to resources when it is deleted and recreated with the same name.
