### ISSUE TITLE
Task: Evaluate OpenMCP internal DNS solution

### ISSUE THREAD

**Issue by reshnm** [openmcp-project/backlog#95]
### Understand the Task

**Description**

OpenMCP spans a network of Kubernetes clusters with operators/services on them that want to communicate with each other across the boundaries of a Kubernetes cluster.
Therefore there is a need for a service to discover the endpount of a remote service via DNS.

All clusters of a OpenMCP landscape should have a subdomain assigned, e.g.:

```
platform.openmcp.cluster
workload01.openmcp.cluster
```

Any service provider can then request a set of subdomains that can be assigned to the service endoints, e.g.:

```
service-1-tenant-a.workload01.openmcp.cluster
```

The service provider then creates a gateway resource that matches this host name.

A service like `external-dns` (https://github.com/kubernetes-sigs/external-dns) could read that host name automatically in the gateway resource and create a DNS entry in the OpenMCP local DNS server that is reachable by all Kubernetes clusters in an OpenMCP landscape.
This DNS service is responsible for resolving the `openmcp.cluster` zone.

### What is required to accept the Task as done.

**Done Criteria**
- [ ] Use external-dns in combination with a local DNS server to set-up a OpenMCP landscape local DNS service with the Kind cluster provider
- [ ] Create a Gateway resource on a Cluster on Cluster A with its hostname and test if it is resolvable from Cluster B
- [ ] Put the results in written form
- [ ] Present results in review/dev sync

**Comment by reshnm** [comment]
Evaluation Complete.
This has resulted in the following ADR: https://github.com/openmcp-project/docs/pull/2

**Comment by In-Ko** [comment]
Question: How is this task related to #43 ? Isn't this the same ?

**Comment by ValentinGerlach** [comment]
> Question: How is this task related to [#43](https://github.com/openmcp-project/backlog/issues/43) ? Isn't this the same ?

No, this issue is about the DNS part whereas the other issue is mostly about HTTP routing (which kinda depends on DNS because we plan to use host-based routing).

**Comment by Kukkerem** [comment]
PoC repository: https://github.tools.sap/openmcp/kind-dns-poc

The original concept is feasible. It currently needs a separate Docker network, which could be avoided by using a kind cluster for the local CoreDNS deployment. With this solution, we can configure etcd with an operator and don't have to use Docker commands at all.

The PoC contains a test application and DNSutils tools for testing in every cluster.

The ValidatingWebhook validation remains to be tested.

**Comment by Diaphteiros** [comment]
@ValentinGerlach and me just tested whether it is possible to get external-dns deployed with a configuration that allows it to manage DNS entries - everything worked fine.

I will quickly dump the providerconfig that worked here, will later also update the examples in the PlatformService DNS repo:
```yaml
apiVersion: dns.openmcp.cloud/v1alpha1
kind: DNSServiceConfig
metadata:
  name: dns
  namespace: openmcp-system
spec:
  secretsToCopy:
    toTargetCluster:
    - source:
        name: route53-access

  externalDNSSource:
    chartName: charts/external-dns
    git:
      url: https://github.com/kubernetes-sigs/external-dns
      interval: 1h
      ref:
        tag: v0.19.0

  externalDNSForPurposes:
  - name: test
    purposeSelector:
      name: test
    helmValues:
      policy: sync
      txtOwnerId: '<environment>.<cluster.namespace>.<cluster.name>'
      sources:
      - service
      - gateway-httproute
      - gateway-tlsroute
      provider:
        name: aws
      env:
      - name: AWS_DEFAULT_REGION
        value: eu-central-1
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /.aws/credentials
      extraVolumes:
      - name: aws-credentials
        secret:
          secretName: route53-access
      extraVolumeMounts:
      - name: aws-credentials
        mountPath: /.aws
        readOnly: true
```

The secret with the route53 credentials (named `route53-access` here) has to look like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: route53-access
  namespace: openmcp-system
stringData:
  credentials: |
    [default]
    aws_access_key_id=<access-key-id>
    aws_secret_access_key=<secret-access-key>
type: Opaque
```
