### ISSUE TITLE
Feature: Include groups extra-scope to kubeconfig of `ManagedControlPlanes`

### ISSUE THREAD

**Issue by GenosseOtt** [openmcp-project/backlog#97]
### Feature Request for

openMCP provisioned `ManagedControlPlanes`

### Understand the problem

When using `Group` subject in authorization section, e.g.
```yaml
authorization:
    roleBindings:
      - role: admin
        subjects:
          - kind: Group
            name: dwc:mcp-access
```
it will require the scope `groups` also included in the authroization request to the identity provider. However the kubeconfig generated on the crate cluster looks like this
```
users:
- name: dwc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=<some value>
      - --oidc-client-id=<some value>
      - --oidc-use-pkce
      - --grant-type=auto
      - --oidc-extra-scope=offline_access
      - --oidc-extra-scope=email
      - --oidc-extra-scope=profile
      command: kubectl
      env: null
      provideClusterInfo: false
``` 
and it will only work if editing the kubeconfig and manually adding `- --oidc-extra-scope=groups`

### Technical Steps
- To be proposed by Engineer

### Context

Using any IDP and groups for authentication to the MCP

### Proposal Acceptance Criteria

- [ ] Kubeconfig should work out of the box for configuration chosen in the MCP CR.
